# Generated by Django 4.2.7 on 2025-12-02 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_booking_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in E.164 format (e.g., +60123456789)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format (e.g., +60123456789)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
